--- #YAML:1.0
name:                Net-Amazon-S3-Tools
version:             0.07
abstract:            Command line tools for Amazon AWS S3
license:             ~
author:              
    - Mark Atwood <mark@fallenpegasus.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::HomeDir:                 0
    Getopt::ArgvFile:              0
    Getopt::Long:                  1
    Net::Amazon::S3:               0
    Net::Amazon::S3::Bucket:       0
    Pod::Usage:                    1
    XML::Writer:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
